apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{.Release.Name}}-frontend
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    route.openshift.io/termination: edge
    route.openshift.io/insecureEdgeTerminationPolicy: Redirect
spec:
  ingressClassName: {{.Values.ingressClassName}}
  {{- if not .Values.ingressTlsDisable }}
  tls:
    - hosts:
        - {{ .Values.host }}
      secretName: {{.Release.Name}}-frontend-tls
  {{ end }}
  rules:
    - host: {{ required ".Values.host is required" .Values.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{.Release.Name}}-frontend
                port:
                  number: 80
